import Head from "next/head";
import About from "../components/About";
import Background from "../components/Background";
import Header from "../components/Header";
import Links from "../components/Links";
export default function Home() {
  return (
    <div className="min-h-screen flex flex-col items-center gap-8 ">
      <Head>
        <title>Anirudh Soni | Linktree | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background />
      <Header />
      <About />
      <Links />
      <footer className="py-8 text-lg">
        &lt;/&gt; by{" "}
        <a
          href="https://anirudhsoni.in"
          className="text-blue-600 font-bold"
          target={"blank"}
        >
          {" "}
          Anirudh Soni{" "}
        </a>
      </footer>
    </div>
  );
}
